# Generated by Django 5.2.7 on 2025-10-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Legislator",
            fields=[
                ("govtrack_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=2)),
                ("district", models.CharField(max_length=10)),
                ("party", models.CharField(max_length=50)),
                ("url", models.CharField(max_length=500)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "legislators",
                "indexes": [
                    models.Index(fields=["state"], name="legislators_state_d42ed5_idx"),
                    models.Index(fields=["party"], name="legislators_party_0858c2_idx"),
                    models.Index(fields=["type"], name="legislators_type_d66552_idx"),
                    models.Index(
                        fields=["birthday"], name="legislators_birthda_cdcaea_idx"
                    ),
                ],
            },
        ),
    ]
