services:
  db:
    image: postgres:15-alpine
    container_name: legislators_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./shared/flask_init.sql:/docker-entrypoint-initdb.d/01-flask-init.sql
      - ./shared/django_init.sql:/docker-entrypoint-initdb.d/02-django-init.sql
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - legislators_network

  flask-api:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    container_name: legislators_flask_api
    environment:
      DATABASE_URL: ${FLASK_DATABASE_URL}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_URL: ${WEATHER_API_URL}
      FLASK_ENV: ${FLASK_ENV}
    ports:
      - "${FLASK_API_PORT}:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./flask-api:/app
    networks:
      - legislators_network
    restart: unless-stopped

  data_ingestion:
    build:
      context: ./flask-api
      dockerfile: Dockerfile
    container_name: legislators_data_ingestion
    environment:
      DATABASE_URL: ${FLASK_DATABASE_URL}
      LEGISLATORS_CSV_URL: ${LEGISLATORS_CSV_URL}
    depends_on:
      db:
        condition: service_healthy
    command: python ingest_data.py
    networks:
      - legislators_network
    profiles:
      - data-load

  django-api:
    build:
      context: ./django-api
      dockerfile: Dockerfile
    container_name: legislators_django_api
    environment:
      POSTGRES_DB: ${DJANGO_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_URL: ${WEATHER_API_URL}
      LEGISLATORS_CSV_URL: ${LEGISLATORS_CSV_URL}
    ports:
      - "${DJANGO_API_PORT}:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./django-api:/app
    networks:
      - legislators_network
    restart: unless-stopped


volumes:
  postgres_data:
    driver: ${VOLUME_DRIVER}

networks:
  legislators_network:
    driver: ${NETWORK_DRIVER}
